title: Zhenkui Yang's Homepage
page-top-title: Zhenkui Yang
top-section-bg-text: It is only with the heart that one can see rightly; what is essential is invisible to the eye.
home-subtitle: Zhenkui Yang&ensp;|&ensp;杨振奎
copyright-text: '&copy; Zhenkui Yang 2023-2025. All Rights Reserved.'
