title: Zhenkui Yang's Homepage
page-top-title: Zhenkui Yang
top-section-bg-text: Be what you wanna be
home-subtitle: Zhenkui Yang&ensp;|&ensp;杨振奎
copyright-text: '&copy; Zhenkui Yang 2023-2025. All Rights Reserved.'
